name: voleep_carclean_frontend
description: Sistema de gestão para lava-rápidos.
publish_to: "none"
version: 1.0.0+32

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.17.1
  flutter_riverpod: ^2.3.2
  dio: ^5.3.3
  go_router: ^10.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.1
  url_launcher: ^6.1.9
  intl: ^0.18.0

  # Code generation related
  json_annotation: ^4.8.0
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.0
  json_serializable: ^6.6.1
  riverpod_generator: ^2.2.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  freezed: ^2.3.3

  # Testing related
  build_test: ^2.1.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/images/
    - environments/

  fonts:
    - family: RobotoSans
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
